### ISSUE TITLE
Theme removes the "remove embeds" button

### ISSUE THREAD

**Issue by SiJiL82** [NYRI4/Couve#11]
When this theme is enabled, the "Remove embeds" button that Discord shows when you post a website link is missing:
Default theme:
![image](https://user-images.githubusercontent.com/65114782/204744295-fa52af68-684b-47c4-a3e2-ce537549a788.png)
Couve:
![image](https://user-images.githubusercontent.com/65114782/204744406-e8d1d5b3-fb6f-481f-9b47-c2e6852f34b0.png)

**Comment by NYRI4** [comment]
Will be fixed in the next push
