### ISSUE TITLE
Overlap with Channel Tabs plugin, the status is in wrong position for own profile

### ISSUE THREAD

**Issue by Dohvakin** [NYRI4/Couve#13]
Hi I use channel tabs plugin and I see that there is a lot of overlap between buttons with that plugin

screenshot 
![image](https://user-images.githubusercontent.com/26587446/215275431-3dd79d16-45ea-4d47-8278-da6cc1766f8e.png)

another issue that I noticed is that for own profile my status is coming in wrong position

![image](https://user-images.githubusercontent.com/26587446/215275532-f6e15431-21e6-4c0f-96eb-a51375b84171.png)

**Comment by NYRI4** [comment]
Should be fixed by now

**Comment by Dohvakin** [comment]
yes it seems to be fixed now
![image](https://user-images.githubusercontent.com/26587446/221345157-f5ea1abc-dbeb-4840-ac1e-755cc849d1c7.png)

thanks I'll be closing the issue then
