### ISSUE TITLE
PFP on DM Profile Modal broken

### ISSUE THREAD

**Issue by SatanaDesigns** [NYRI4/Couve#15]
![Discord_t0SULLuYJF](https://user-images.githubusercontent.com/72283516/216227126-04b1529c-264e-4b8e-b050-e8f93b9d0223.png)
In DMS, the profile modals pfp border radius is messed.

**Comment by SatanaDesigns** [comment]
(the pfp is square, while the border behind it is a circle)

**Comment by NYRI4** [comment]
You have an outdated version of the theme, download the theme again here : https://betterdiscord.app/theme/Couve

**Comment by SatanaDesigns** [comment]
oh, sorry
