### ISSUE TITLE
Weird server folder aura

### ISSUE THREAD

**Issue by Nicd5a** [NYRI4/Couve#18]
While using the new color themes on discord this weird aura appears in the server folders. 
![image](https://user-images.githubusercontent.com/128427221/226471162-b42a592c-e96e-49c0-8a54-53be48e61cb1.png)

**Comment by Tawnee323** [comment]
Have the same issue. I think it’s a conflict between bo5h folder icons loading at the same time.

**Comment by D3anDark** [comment]
<img width="41" alt="image" src="https://user-images.githubusercontent.com/93433446/226561330-2552b3f5-e488-49f5-a514-6df9eeee08e1.png">
I don't have anything like that (try paste CSS code to quick CSS console)

**Comment by Nicd5a** [comment]
thats because ure on plain dark mode, I mean the new discord color themes

**Comment by NYRI4** [comment]
I won't support discord themes in all my themes, pick one not two
