### ISSUE TITLE
Don't see that line after type > or >>>

### ISSUE THREAD

**Issue by D3anDark** [NYRI4/Couve#19]
If I type or see >, >>> I don't see this line after type it and it's raging me because I using it so many times and when I don't see it I was so confuse
<img width="12" alt="image" src="https://user-images.githubusercontent.com/93433446/226560755-6143ef81-01f9-4955-9fed-16f5658a180a.png">
That's this line after type > or >>>

**Comment by NYRI4** [comment]
![image](https://user-images.githubusercontent.com/65369563/227134063-6e7bbff0-1045-4cf1-9f32-4b266ff413aa.png)
 works like it's supposed to be 🤔
