### ISSUE TITLE
Resolution problem

### ISSUE THREAD

**Issue by MashroSac** [NYRI4/Couve#24]
![image](https://github.com/NYRI4/Couve/assets/79238788/3cc6d7ad-89c7-4bfe-9763-8664ef3dd28b)

This
resolution problem
idk how to fix it 
you see the edit button going off screen
this happens with everything else
Im on vencord
![image](https://github.com/NYRI4/Couve/assets/79238788/1d026037-be91-4f61-ab2f-6e82422320fe)
this is another example
the server picture just goes offscreen
![image](https://github.com/NYRI4/Couve/assets/79238788/347845e0-2d08-4753-8908-4b966c4bd8bc)
and this too 
again my pfp cuts off on the bottom

**Comment by NYRI4** [comment]
I know that's an old issue but if you can still tell me the steps to reproduce the server list issues that would be great, else you can close this, I fixed the profile setting part
