### ISSUE TITLE
Some buttons in the voice call are still circles.

### ISSUE THREAD

**Issue by MrZomka** [NYRI4/Couve#25]
Does anyone know how to fix this? I'm on Vencord.

![image](https://github.com/NYRI4/Couve/assets/25344028/6208bf32-2e5e-4e97-b074-1044c2d60b16)

**Comment by NYRI4** [comment]
Issue fixed

**Comment by MrZomka** [comment]
Nothing changed though :/
![image](https://github.com/NYRI4/Couve/assets/25344028/4215cb60-ff4c-421b-a084-26c09fb0595f)

**Comment by NYRI4** [comment]
Well yeah now I saw that it is specificaly on a DM call, you need to be more precise

**Comment by NYRI4** [comment]
Should be better now
