### ISSUE TITLE
Setting the new "display name" feature breaks the change status menu a little

### ISSUE THREAD

**Issue by SoaringGecko** [NYRI4/Couve#26]
![image](https://github.com/NYRI4/Couve/assets/48862796/df4383d1-6d84-40fb-ba63-980584033782)

The normal view work fine though
![image](https://github.com/NYRI4/Couve/assets/48862796/c5e32f4b-b419-41d7-a9ce-d8f390451e06)

**Comment by NYRI4** [comment]
This should be better by now, pronouns works well with it now too
