### ISSUE TITLE
Some margin errors ++

### ISSUE THREAD

**Issue by HaxWire** [NYRI4/Couve#36]
~~Random box instead of online circle on online people~~
~~Tried restarting BDD but dosnt seem to fix the  issue~~
![image](https://github.com/NYRI4/Couve/assets/19493307/e82c3d47-51e2-4658-a866-89249de18335)

Voice chat "subjects" also seem to get sqeezed into the first person in the VC
![image](https://github.com/NYRI4/Couve/assets/19493307/0b1fdeaa-b49b-4c38-999d-d1d15a804f02)

A little pet peve but the margins on these are messed up 
![image](https://github.com/NYRI4/Couve/assets/19493307/5178a069-a992-499d-913a-bb6d112af326)
![image](https://github.com/NYRI4/Couve/assets/19493307/ccd7f464-9dc6-47d5-9c64-c13ef9bfd785)

Expect that, brilliant theme.

**Comment by HaxWire** [comment]
My bad. Its clearly when people are on phone

**Comment by NYRI4** [comment]
I can't reproduce the margin gap you have on user modals
