### ISSUE TITLE
Discord broke themes

### ISSUE THREAD

**Issue by Splatube** [NYRI4/Couve#37]
Discord pushed an updated that broke a ton of theme related stuff so couve is bugged

**Comment by Remco0o** [comment]
will be fixed if they merge my pull request

**Comment by Splatube** [comment]
Don't think it'd fix everything, but most of it can be fixed with https://syndishanx.github.io/Website/Update_Classes.html

**Comment by Remco0o** [comment]
> Don't think it'd fix everything, but most of it can be fixed with https://syndishanx.github.io/Website/Update_Classes.html (Using a local version of the theme with this tool and it works pretty well)

My pull request isnt merged yet

**Comment by P-o-u-t** [comment]
Greetings Nyria, and other developers.

Couve's custom profiles and border radius' for some parts of Discord are broken, 
(Clicking your name at the bottom left, opening your profile anywhere in Discord, and other users profiles)
appreciate the hard work as usual :>

**Comment by posrgl** [comment]
Giving the developer a poke again, @NYRI4 ?  (Side note, i'd like to join development for this)

**Comment by NYRI4** [comment]
Guess most is fixed, closing.
