### ISSUE TITLE
Polls feature

### ISSUE THREAD

**Issue by SoaringGecko** [NYRI4/Couve#38]
While not perfect, changing `.container__0bd59 {background-color: var(--card-secondary-bg);}` to `.container__0bd59 {background-color: var(--background-secondary);}` does help make these match the theme a bit better (as a temporary fix)

![image](https://github.com/NYRI4/Couve/assets/48862796/b2824306-5af5-4501-87c7-9031421f647f)
![image](https://github.com/NYRI4/Couve/assets/48862796/92a41970-d91d-444a-9c0f-8c11e2dece2b)

**Comment by SoaringGecko** [comment]
> wait where did you change it. just in the css file or

inspect element lol

**Comment by NYRI4** [comment]
Fixed.
