### ISSUE TITLE
User popout broken

### ISSUE THREAD

**Issue by Flonky** [NYRI4/Couve#4]
## What's the issue?
The profile picture is over the user name in the user popout.

## Screenshot
![grafik](https://user-images.githubusercontent.com/64008721/123658284-da283f80-d831-11eb-9bf7-6fb4e6b95234.png)

**Comment by NYRI4** [comment]
Reload your client, I just fixed it

**Comment by Flonky** [comment]
Oh yeah, thank you!
Appreciate your work on the theme^^
