### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by S409ISDAD** [NYRI4/Couve#41]
![image_2024-06-25_215925267](https://github.com/NYRI4/Couve/assets/129562233/cc908d1a-933d-4d16-8924-0e628dd8af6c)
![image_2024-06-25_215932450](https://github.com/NYRI4/Couve/assets/129562233/eb014bff-1e4d-4632-ae10-c485c0fc75a4)
![image_2024-06-25_215937218](https://github.com/NYRI4/Couve/assets/129562233/e3638e39-7996-4074-9fa3-3ec439c32b29)

These are all the bugs i have found.

**Comment by S409ISDAD** [comment]
heres a better profile:
![image_2024-06-25_220048710](https://github.com/NYRI4/Couve/assets/129562233/28713517-3c56-45e0-a599-5c67a434aa85)

**Comment by S409ISDAD** [comment]
Also for some reason the profiles on bots are find but on users its messed up.

**Comment by HaHAjax** [comment]
Full profiles also don't load anything (for me, at least):
![image](https://github.com/NYRI4/Couve/assets/128398800/2a0ca4ad-6efc-4bc6-9e1d-f9c557361ae3)

**Comment by 0385mrcoolman** [comment]
Yep, I have also seen most of these bugs.

**Comment by S409ISDAD** [comment]
Another bug
![Uploading image_2024-07-18_174750701.png…]()
:

**Comment by S409ISDAD** [comment]
![image_2024-07-18_174813097](https://github.com/user-attachments/assets/f1e5b350-f171-442e-a4ee-465d17984fdc)

**Comment by walbjorn** [comment]
I also have these bugs. Would love to see them fixed if there's time someday - your theme is the best <3

**Comment by 0385mrcoolman** [comment]
I already switched to another theme. Feels like they've honestly just abandoned their projects and hope the community solves all of their problems.

**Comment by S409ISDAD** [comment]
> I already switched to another theme. Feels like they've honestly just abandoned their projects and hope the community solves all of their problems.

same tbh im using the spotify theme and think its alot better ngl

**Comment by NYRI4** [comment]
I guess most of the bugs reported here are now fixed so I'm closing this issue.
